version: '3'

services:
  frontend:
    build:
      context: ../File-managment-front
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build:
      context: ../file-managment-back
    ports:
      - '5000:5000'
    env_file:
      - ../file-managment-back/.env
